# Generated by Django 4.2.26 on 2025-11-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_answer_lines',
            field=models.JSONField(blank=True, db_column='answerAnswerLines', default=list, help_text='Stores answer line configurations in answer section'),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_image_positions',
            field=models.JSONField(blank=True, db_column='answerImagePositions', default=dict, help_text='Stores x,y coordinates for positioned images in answer'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_answer_lines',
            field=models.JSONField(blank=True, db_column='questionAnswerLines', default=list, help_text='Stores answer line configurations in question section'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_image_positions',
            field=models.JSONField(blank=True, db_column='questionImagePositions', default=dict, help_text='Stores x,y coordinates for positioned images in question'),
        ),
    ]
