# Generated by Django 4.2.26 on 2025-11-11 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_question_answer_answer_lines_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='time_allocation',
            field=models.IntegerField(default=120, help_text='Time allocation in minutes'),
        ),
        migrations.AddField(
            model_name='paper',
            name='total_marks',
            field=models.IntegerField(default=80, help_text='Total marks for this paper'),
        ),
        migrations.AddField(
            model_name='question',
            name='kcse_question_type',
            field=models.CharField(blank=True, choices=[('name_identify', 'Name/Identify'), ('state_give_reasons', 'State/Give Reasons'), ('distinguish', 'Distinguish/Differentiate'), ('explain_account', 'Explain/Account For'), ('describe', 'Describe'), ('calculate', 'Calculate')], help_text='KCSE-specific question type for Biology Paper 1 generation', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='max_marks',
            field=models.IntegerField(default=10, help_text='Maximum marks this topic should have in a generated paper'),
        ),
        migrations.AddField(
            model_name='topic',
            name='min_marks',
            field=models.IntegerField(default=4, help_text='Minimum marks this topic should have in a generated paper'),
        ),
        migrations.CreateModel(
            name='PaperConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('one_mark_min_percent', models.FloatField(default=30.0, help_text='Minimum percentage of 1-mark questions')),
                ('one_mark_max_percent', models.FloatField(default=40.0, help_text='Maximum percentage of 1-mark questions')),
                ('two_mark_min_percent', models.FloatField(default=35.0, help_text='Minimum percentage of 2-mark questions')),
                ('two_mark_max_percent', models.FloatField(default=45.0, help_text='Maximum percentage of 2-mark questions')),
                ('three_mark_min_percent', models.FloatField(default=15.0, help_text='Minimum percentage of 3-mark questions')),
                ('three_mark_max_percent', models.FloatField(default=25.0, help_text='Maximum percentage of 3-mark questions')),
                ('four_mark_min_percent', models.FloatField(default=0.0, help_text='Minimum percentage of 4-mark questions')),
                ('four_mark_max_percent', models.FloatField(default=5.0, help_text='Maximum percentage of 4-mark questions')),
                ('name_identify_min_percent', models.FloatField(default=20.0, help_text='Minimum percentage of name/identify questions')),
                ('name_identify_max_percent', models.FloatField(default=30.0, help_text='Maximum percentage of name/identify questions')),
                ('state_reasons_min_percent', models.FloatField(default=25.0, help_text='Minimum percentage of state/give reasons questions')),
                ('state_reasons_max_percent', models.FloatField(default=35.0, help_text='Maximum percentage of state/give reasons questions')),
                ('distinguish_min_percent', models.FloatField(default=10.0, help_text='Minimum percentage of distinguish questions')),
                ('distinguish_max_percent', models.FloatField(default=15.0, help_text='Maximum percentage of distinguish questions')),
                ('explain_min_percent', models.FloatField(default=20.0, help_text='Minimum percentage of explain questions')),
                ('explain_max_percent', models.FloatField(default=30.0, help_text='Maximum percentage of explain questions')),
                ('describe_min_percent', models.FloatField(default=10.0, help_text='Minimum percentage of describe questions')),
                ('describe_max_percent', models.FloatField(default=20.0, help_text='Maximum percentage of describe questions')),
                ('calculate_min_percent', models.FloatField(default=0.0, help_text='Minimum percentage of calculate questions')),
                ('calculate_max_percent', models.FloatField(default=5.0, help_text='Maximum percentage of calculate questions')),
                ('min_questions', models.IntegerField(default=25, help_text='Minimum number of questions in paper')),
                ('max_questions', models.IntegerField(default=30, help_text='Maximum number of questions in paper')),
                ('max_backtracking_attempts', models.IntegerField(default=100, help_text='Maximum backtracking attempts before restart')),
                ('max_generation_attempts', models.IntegerField(default=5, help_text='Maximum full generation attempts')),
                ('instructions', models.TextField(default='Answer all questions in the spaces provided on this paper.', help_text='Standard instructions for candidates')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='api.paper')),
            ],
            options={
                'db_table': 'paper_configurations',
                'ordering': ['paper'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedPaper',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unique_code', models.CharField(help_text='Unique identifier for this generated paper', max_length=20, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('validated', 'Validated'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('question_ids', models.JSONField(help_text='Ordered list of question IDs in this paper')),
                ('selected_topics', models.JSONField(help_text='List of topic IDs selected for generation')),
                ('topic_adjustments', models.JSONField(blank=True, help_text='Proportional adjustments made to topic mark ranges', null=True)),
                ('total_marks', models.IntegerField()),
                ('total_questions', models.IntegerField()),
                ('mark_distribution', models.JSONField(help_text='Distribution of questions by mark value')),
                ('topic_distribution', models.JSONField(help_text='Distribution of marks by topic')),
                ('question_type_distribution', models.JSONField(help_text='Distribution of question types')),
                ('validation_passed', models.BooleanField(default=False)),
                ('validation_report', models.JSONField(blank=True, help_text='Detailed validation results', null=True)),
                ('generation_attempts', models.IntegerField(default=1, help_text='Number of attempts before successful generation')),
                ('backtracking_count', models.IntegerField(default=0, help_text='Number of backtracking operations performed')),
                ('generation_time_seconds', models.FloatField(blank=True, help_text='Time taken to generate this paper', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_papers', to=settings.AUTH_USER_MODEL)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_papers', to='api.paper')),
            ],
            options={
                'db_table': 'generated_papers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['paper', 'status'], name='generated_p_paper_i_7e5701_idx'), models.Index(fields=['unique_code'], name='generated_p_unique__30dccb_idx')],
            },
        ),
    ]
