# Generated by Django 4.2.26 on 2025-11-13 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_add_is_nested_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='is_nested',
            field=models.BooleanField(default=False, help_text='True if question has multiple parts (a, b, c, d). Only the total marks need to be specified.'),
        ),
        migrations.AlterField(
            model_name='question',
            name='nested_parts',
            field=models.JSONField(blank=True, default=list, help_text='OPTIONAL: Can store part breakdowns if needed, but not required for paper generation.', null=True),
        ),
    ]
