# Generated by Django 4.2.26 on 2025-11-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_make_nested_parts_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedpaper',
            name='coverpage_data',
            field=models.JSONField(blank=True, help_text='Coverpage information (school name, logo, instructions, etc.)', null=True),
        ),
    ]
