# Generated by Django 4.2.26 on 2025-12-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_add_coverpage_data_to_generated_paper'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedpaper',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional metadata about the paper (paper_type, generation_algorithm, sections, etc.)', null=True),
        ),
    ]
