# Generated by Django 4.2.26 on 2025-12-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_add_paper2_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_essay',
            field=models.BooleanField(default=False, help_text='True if this question is an essay type.'),
        ),
        migrations.AddField(
            model_name='question',
            name='is_graph',
            field=models.BooleanField(default=False, help_text='True if this question requires a graph as part of the answer.'),
        ),
    ]
