# Generated by Django 4.2.26 on 2025-12-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_question_is_essay_question_is_graph'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_map',
            field=models.BooleanField(default=False, help_text='True if this question requires a map as part of the answer.'),
        ),
    ]
