# Generated by Django 4.2.26 on 2026-03-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_question_is_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='duration_hours',
            field=models.IntegerField(default=2, help_text='Duration in hours (for display purposes)'),
        ),
        migrations.AddField(
            model_name='paper',
            name='duration_minutes',
            field=models.IntegerField(default=0, help_text='Additional minutes beyond hours (for display purposes, 0-59)'),
        ),
        migrations.AddField(
            model_name='topic',
            name='is_comprehension',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='is_isimu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='is_lugha',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='is_step',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='is_summary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['-created_at'], name='questions_created_fc8d7e_idx'),
        ),
    ]
